### ISSUE TITLE
Parsing of PwCalculation broken for Quantum ESPRESSO 6.2

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-quantumespresso#52]
The output of the volume in the stdout of `pw.x` has changed in `6.2` to include the volume also in units of Angstrom cubed.

```
447.46796 a.u.^3 (    66.30791 Ang^3 )
```
This break the parsing string for the volume in `aiida_quantumespresso/parsers/raw_parser_pw.py` on line `1136`:
```
volume = float(line.split('=')[1].split('(a.u.)^3')[0])
```

This is probably one of many format changes that will break parsing of `PwCalculation` run with `6.2`

**Comment by quanshengwu** [comment]
This was fixed with 

```
                    try:
                        volume = float(line.split('=')[1].split('a.u.^3')[0])
                    except:
                        volume = float(line.split('=')[1].split('(a.u.)^3')[0])
```

**Comment by sphuber** [comment]
I have compiled Quantum ESPRESSO v6.2 myself, both with and without the option `-D__OLDXML` to the `MANUAL_DFLAGS` in the `make.inc` file and I cannot reproduce this error. In my standard output file the line with the volume reads:

```
unit-cell volume          =     275.9734 (a.u.)^3
```

I am not sure how Quan Sheng got the output with the added volume in units of Angstrom cubed. @quanshengwu could you tell us how you compiled the version of pw that produced the problematic output?

**Comment by sphuber** [comment]
The previous statement was based on the results of a simple `scf` calculation. Having run a `vc-relax` I can now confirm that the output does contain the new format, when it prints the volume of the new structure after a completed BFGS step:

```
new unit-cell volume =   1113.13435 a.u.^3 (   164.94949 Ang^3 )
```

However, the parsing does not fail for me. So I still cannot fully reproduce the problem

**Comment by bonfus** [comment]
Same here, using development version of pw (`__OLD_XML` no longer available).

    *** 3 LOG MESSAGES:
    +-> WARNING at 2018-11-15 10:47:34.503327+00:00
     | There was nonempty stderr in the whoami command: manpath: warning: $MANPATH set, ignoring /etc/man_db.conf
    +-> ERROR at 2018-11-15 11:04:21.800386+00:00
     | The xml output file 'data-file.xml' was not found but is required
    +-> REPORT at 2018-11-15 11:04:21.986844+00:00
     | [410|ContinueJobCalculation|on_except]: Traceback (most recent call last):
     |   File "/home/pie/venvs/aiida/lib/python2.7/site-packages/plumpy/process_states.py", line 228, in execute
     |     result = self.run_fn(*self.args, **self.kwargs)
     |   File "/home/pie/venvs/aiida/lib/python2.7/site-packages/aiida/work/job_processes.py", line 645, in retrieved
     |     exit_code = execmanager.parse_results(self.calc, retrieved_temporary_folder)
     |   File "/home/pie/venvs/aiida/lib/python2.7/site-packages/aiida/daemon/execmanager.py", line 446, in parse_results
     |     exit_code, new_nodes_tuple = parser.parse_from_calc(retrieved_temporary_folder)
     |   File "/home/pie/venvs/aiida/lib/python2.7/site-packages/aiida/parsers/parser.py", line 90, in parse_from_calc
     |     return self.parse_with_retrieved(retrieved)
     |   File "/home/pie/venvs/aiida/lib/python2.7/site-packages/aiida_quantumespresso/parsers/pw.py", line 96, in parse_with_retrieved
     |     out_dict, trajectory_data, structure_data, bands_data, raw_successful = parse_raw_output(*parsing_args)
     |   File "/home/pie/venvs/aiida/lib/python2.7/site-packages/aiida_quantumespresso/parsers/raw_parser_pw.py", line 98, in parse_raw_output
     |     out_data,trajectory_data,critical_messages = parse_pw_text_output(out_lines, xml_data, structure_data, input_dict, parser_opts)
     |   File "/home/pie/venvs/aiida/lib/python2.7/site-packages/aiida_quantumespresso/parsers/raw_parser_pw.py", line 1129, in parse_pw_text_output
     |     volume = float(line.split('=')[1].split('(a.u.)^3')[0])
     | ValueError: invalid literal for float(): 852.02326 a.u.^3 (   126.25682 Ang^3 )

Solution already posted by @quanshengwu .
